

//USUARIOS


// Crear usuario
###
POST http://localhost:3000/crearusuario  HTTP/1.1
Content-Type: application/json

{
    "username": "@santipajaslocas",
    "description": "juniormanda",
    "name": "soysanty",
    "email": "fsantyteo@gmail.com"
}


// ver todos los usuarios
###
GET http://localhost:3000/usuarios HTTP/1.1


// ver un usuario especifico
###
GET http://localhost:3000/usuario/6364989a682b1931e13b9e15 HTTP/1.1


// actualizar un usuario
###
PUT http://localhost:3000/actusuario/6364989a682b1931e13b9e15 HTTP/1.1
Content-Type: application/json

{
    "username": "@riveraangel",
    "description": "Melany te amo",
    "name": "AngelLBK",
    "email": "angelitorivera@gmail.com"
}


// eliminar  un usuario
###
DELETE http://localhost:3000/eliminarusuario/636436b7380794beef4f092f HTTP/1.1


//TUITS


// tuitear
###
POST http://localhost:3000/tuitear  HTTP/1.1
Content-Type: application/json

{
    "text": "prueba 10",
    "valecita": "6364990d682b1931e13b9e1c"
}


// ver todos los tuits
###
GET http://localhost:3000/tuits HTTP/1.1


// ver todos los tuits de un usuario
###
GET http://localhost:3000/tuitsde/6364990d682b1931e13b9e1c HTTP/1.1


// editar un tuit
###
PUT http://localhost:3000/edittuit/6364a94fc2ae9828472f74c1 HTTP/1.1
Content-Type: application/json

{
    "text": "salsita y berbena"
}


// eliminar  un tuit
###
DELETE http://localhost:3000/borrartuit/6364a952c2ae9828472f74c7 HTTP/1.1


// Seguir
###
POST http://localhost:3000/seguir  HTTP/1.1
Content-Type: application/json

{
    "seguido": "6364989a682b1931e13b9e15",
    "seguidor": "63649933682b1931e13b9e1e"
}


// seguidores de un usuario
###
GET http://localhost:3000/seguidores/6364989a682b1931e13b9e15 HTTP/1.1


// seguidos de un usuario
###
GET http://localhost:3000/seguidos/63649933682b1931e13b9e1e HTTP/1.1


// dejar de seguir
###
DELETE http://localhost:3000/dejardeseguir HTTP/1.1
Content-Type: application/json

{
    "seguido": "6364989a682b1931e13b9e15",
    "seguidor": "63649933682b1931e13b9e1e"
}


// dar like
###
POST http://localhost:3000/darlike  HTTP/1.1
Content-Type: application/json

{
    "like": "63649933682b1931e13b9e1e",
    "tuit": "6364a954c2ae9828472f74ce"
}
